DROP SEQUENCE MYBOARDSEQ;
DROP TABLE MYBOARD;

CREATE SEQUENCE MYBOARDSEQ;

CREATE TABLE MYBOARD(
	MYNO NUMBER PRIMARY KEY,
	MYNAME VARCHAR2(100) NOT NULL,
	MYTITLE VARCHAR2(1000) NOT NULL,
	MYCONTENT VARCHAR2(4000) NOT NULL,
	MYDATE DATE NOT NULL
);

INSERT INTO MYBOARD
VALUES(MYBOARDSEQ.NEXTVAL, '관리자', '스스로 해봅시다.', '아까 적은 종이보고, 직접 하나씩 만들어 보세요.', SYSDATE);

SELECT MYNO, MYNAME, MYTITLE, MYCONTENT, MYDATE
FROM MYBOARD
ORDER BY MYNO DESC;